[DOR-1565] Split up dorado_test
Also unify the windows one with the non-windows one.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -561,7 +561,7 @@ build_archive:macos:arm:
 
 # Test stage components
 
-.test_dorado:
+.test_dorado_common:
   stage: test
   variables:
     GIT_STRATEGY: none
@@ -569,7 +569,6 @@ build_archive:macos:arm:
     BATCH: 384
     VALIDATE_FASTQ: 1
     VALIDATE_BAM: 1
-    PYTHON: python3
   script:
     - !reference [.create_venv]
     # Do everything inside a newly created folder, since some runners only run
@@ -579,39 +578,49 @@ build_archive:macos:arm:
     - cd test_archive
     - mv ../dist ../tests.archive .
     - !reference [.unzip_test_files]
-    - bash ./tests/test_simple_basecaller_execution.sh ./dist/bin/dorado ${MODEL} ${BATCH}
-    - bash ./tests/test_nested_output_structure.sh ./dist/bin/dorado ${MODEL} ${BATCH}
-    - bash ./tests/test_expected_logging.sh ./dist/bin/dorado ${MODEL} ${BATCH}
-    - bash ./tests/test_model_resolution.sh ./dist/bin/dorado
-    - bash ./tests/test_dorado_correct.sh ./dist/bin/dorado
-    - bash ./tests/test_dorado_correct_cram.sh ./dist/bin/dorado
-    - bash ./tests/test_dorado_polish.sh ./dist/bin/dorado
-    - bash ./tests/test_dorado_variant.sh ./dist/bin/dorado
+    # Manually sharding the tests based on how long they take (in an arm64 job).
+    # Note that Windows can't run the cram tests (shard 1 and 2).
+    - if [[ ${TEST_SHARD} -eq 0 ]] ; then
+    -   bash ./tests/test_simple_basecaller_execution.sh ./dist/bin/dorado ${MODEL} ${BATCH}  # 11m
+    -   bash ./tests/test_nested_output_structure.sh ./dist/bin/dorado ${MODEL} ${BATCH}      # <1m
+    -   bash ./tests/test_expected_logging.sh ./dist/bin/dorado ${MODEL} ${BATCH}             # <1m
+    -   bash ./tests/test_model_resolution.sh ./dist/bin/dorado                               # <1m
+    -   bash ./tests/test_dorado_correct.sh ./dist/bin/dorado                                 # <1m
+    - elif [[ ${TEST_SHARD} -eq 1 ]] ; then
+    -   bash ./tests/test_dorado_correct_cram.sh ./dist/bin/dorado                            # 10m
+    -   bash ./tests/test_dorado_variant.sh ./dist/bin/dorado                                 # 3m
+    - elif [[ ${TEST_SHARD} -eq 2 ]] ; then
+    -   bash ./tests/test_dorado_polish.sh ./dist/bin/dorado                                  # 16m
+    - else
+    -   echo "Invalid shard '${TEST_SHARD}'"
+    -   exit 1
+    - fi
   artifacts:
     when: on_failure
     paths:
       - test_archive/tests
     expire_in: 1 day
 
-.test_dorado_windows:
-  stage: test
+.test_dorado:
+  extends:
+    - .test_dorado_common
   variables:
-    GIT_STRATEGY: none
+    PYTHON: python3
+  parallel:
+    matrix:
+      - TEST_SHARD: [0, 1, 2]
+
+.test_dorado_windows:
+  extends:
+    - .test_dorado_common
+  variables:
     SAMTOOLS_UNAVAILABLE: sadly_yes
-    VALIDATE_FASTQ: 1
+    VALIDATE_BAM: 0
     PYTHON: python
-  script:
-    # Do everything inside a newly created folder, since some runners only run
-    # tests and hence never perform a git clean.
-    - rm -rf test_archive
-    - mkdir test_archive
-    - cd test_archive
-    - mv ../dist ../tests.archive .
-    - !reference [.unzip_test_files]
-    - bash ./tests/test_simple_basecaller_execution.sh ./dist/bin/dorado ${MODEL} ${BATCH}
-    - bash ./tests/test_expected_logging.sh ./dist/bin/dorado ${MODEL} ${BATCH}
-    - bash ./tests/test_model_resolution.sh ./dist/bin/dorado
-    - bash ./tests/test_dorado_correct.sh ./dist/bin/dorado
+  parallel:
+    matrix:
+      # Not running shards 1 or 2. See .test_dorado_common
+      - TEST_SHARD: [0]
 
 .extract_archive:
   script:
